apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: febri4n-capi-k0smotron-worker-health
  namespace: default
spec:
  clusterName: febri4n-capi-k0smotron
  nodeStartupTimeout: 10m
  maxUnhealthy: 40%
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: febri4n-capi-k0smotron
      #cluster.x-k8s.io/deployment-name: febri4n-nyoba-capi-kamaji-worker
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 300s
    - type: Ready
      status: "False"
      timeout: 300s